### ISSUE TITLE
Add docs for usage

### ISSUE THREAD

**Issue by paulirish** [fossapps/MergeWhenReady#1]
I'm interested in using this but don't know how to get started.... could you add some documentation on how to use this app?

**Comment by cyberhck** [comment]
thanks for opening a issue :) it's very simple actually, simple install this app on all the repo you're interested in (it can be all of them), then whenever you're ready with your PR, add the label this app will create to your PR, and that's all :)

Let me know if you need any help or if you figured it out, you can close this issue :)
