### ISSUE TITLE
Feature request to add option to delete the branch after merging

### ISSUE THREAD

**Issue by Svantulden** [fossapps/MergeWhenReady#3]
**Is your feature request related to a problem? Please describe.**
Our workflow is that we always delete the PR branch when we merge the PR. 

**Describe the solution you'd like**
An option for the app like a checkbox per repo would be nice to enable deletion of the branch (if possible).

**Comment by cyberhck** [comment]
Hello there, well I can't automatically add checkboxes to gh if that's what you mean, but I know your situation, there are two ways to solve this problem, and unfortunately I'll not implement this functionality on mine, (I think single responsibility principle wins here)

- use github's auto branch delete (pro: don't need app, con: you have to configure for each repo)
- use https://github.com/SvanBoxel/delete-merged-branch/ (pro: don't need to configure per repo, you can enable for everything, con: app has to be installed, but I wouldn't call it con anyway)
